#!/usr/bin/awk
BEGIN{ 
	idx = 0;max = 1000; getline;
	for( i = 0; i < max; i++ ){ map[i] = "false"}
	current_id = $1; arr[idx++] = $2;map[$2] = "true"
}
$1 == current_id {
	arr[idx++] = $2;
	map[$2] = "true";
}
$1 != current_id {
	printf "TID_%s" ,current_id;
	for( i = 0; i < max; i++ ){ printf ",%s", map[i] }
	print "";
	for( i = 0; i < idx; i++ ){ map[arr[i]] = "false" }
	current_id = $1; delete arr; idx = 0; arr[idx++] = $2;map[$2] = "true";
}
END{
	printf "TID_%s" ,current_id;
	for( i = 0; i < max; i++ ){ printf ",%s", map[i] }
	print "";
}
