#!/usr/bin/awk
BEGIN{
	max = 10;
    for( i = 0; i < max; i++ ){
        printf "item_%d", i ;
		if( i < max - 1 ){ printf ","; }
    }
	print "";
	i = 0; getline; current_id = $1; arr[i++] = $2;
}
$1 == current_id { 
	arr[i++] = $2
}
$1 != current_id {
	for (i in arr) {printf "%s ",arr[i]} ;print ".";
	current_id = $1; i = 0;delete arr;
	arr[i++] = $2;
}
END{ for (i in arr) {printf "%s ",arr[i]} ;print "."; }
